# app.py — FINAL WITH PDF DOWNLOAD (Professional, client-ready)

import streamlit as st
import pandas as pd
import numpy as np
from mlxtend.frequent_patterns import fpgrowth, association_rules
from mlxtend.preprocessing import TransactionEncoder
import plotly.express as px
import time
from fpdf import FPDF   # ← NEW: for PDF generation

# === PAGE CONFIG & BRANDING ===
st.set_page_config(page_title="BundleAI", layout="wide")
st.markdown("""
<div style="text-align:center; padding:30px; background:#1e3d1e; color:white; border-radius:15px; margin-bottom:30px">
<h1>BundleAI</h1>
<h3>Market Basket Intelligence • Built by Freda Erinmwingbovo</h3>
</div>
""", unsafe_allow_html=True)

st.markdown("### Upload your transactions CSV (one row = one basket, items separated by commas)")

uploaded_file = st.file_uploader("", type=['csv'])

if uploaded_file is not None:
    with st.spinner("BundleAI is analysing your data..."):
        # [Same data loading & cleaning code as before — unchanged]
        df = pd.read_csv(uploaded_file, header=None, dtype=str)
        raw = df.fillna('').astype(str).apply(lambda row: [x.strip().title() for x in row if x.strip()], axis=1).tolist()
        cleaned = []
        for basket in raw:
            seen = set()
            uniq = [x for x in basket if x and x not in seen and not seen.add(x)]
            if uniq:
                cleaned.append(uniq)
        
        n_transactions = len(cleaned)
        if n_transactions == 0:
            st.error("No valid transactions found.")
            st.stop()
        
        te = TransactionEncoder()
        te_ary = te.fit(cleaned).transform(cleaned)
        df_onehot = pd.DataFrame(te_ary, columns=te.columns_)
        
        min_support = max(0.01, 100/n_transactions)
        freq = fpgrowth(df_onehot, min_support=min_support, use_colnames=True, max_len=6)
        rules = association_rules(freq, metric="lift", min_threshold=1.0)
        
        elite = rules[(rules['confidence'] >= 0.5) & (rules['lift'] >= 2.0)].copy()
        elite['impact'] = elite['lift'] * elite['support'] * n_transactions
        elite = elite.sort_values('impact', ascending=False).head(25).reset_index(drop=True)
        
        if elite.empty:
            st.warning("No strong bundles found.")
            st.stop()
        
        top_items = df_onehot.sum().sort_values(ascending=False).head(20)

    st.success(f"BundleAI discovered {len(elite)} elite bundles!")

    # === DISPLAY RESULTS ===
    col1, col2 = st.columns([1.2, 1])
    with col1:
        fig1 = px.bar(top_items, title="Top 20 Best-Selling Items", color=top_items.values, color_continuous_scale="emrld")
        st.plotly_chart(fig1, use_container_width=True)
    with col2:
        elite['Bundle'] = elite.apply(lambda r: f"{', '.join(sorted(list(r.antecedents)))} → {', '.join(sorted(list(r.consequents)))}", axis=1)
        show = elite[['Bundle', 'lift', 'confidence']].round(3)
        show.columns = ['Bundle Insight', 'Lift', 'Confidence']
        st.dataframe(show.head(10).style.background_gradient(cmap='Greens', subset=['Lift']), use_container_width=True)

    # === GENERATE PDF REPORT ===
    def create_pdf():
        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Arial", size=12)
        pdf.set_fill_color(30, 61, 30)
        pdf.set_text_color(255, 255, 255)
        pdf.cell(0, 15, "BundleAI – Market Basket Intelligence Report", 1, 1, 'C', fill=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(10)
        pdf.set_font("Arial", size=11)
        pdf.cell(0, 10, f"Transactions analyzed: {n_transactions:,}", 0, 1)
        pdf.cell(0, 10, f"Top 5 best-sellers: {', '.join(top_items.head(5).index.tolist())}", 0, 1)
        pdf.ln(5)
        pdf.set_font("Arial", 'B', size=12)
        pdf.cell(0, 10, "Top 5 Recommended Bundles", 0, 1)
        pdf.set_font("Arial", size=11)
        for i in range(5):
            row = elite.iloc[i]
            ants = ', '.join(sorted(list(row.antecedents)))
            cons = ', '.join(sorted(list(row.consequents)))
            pdf.cell(0, 10, f"{i+1}. Customers who buy {ants} also buy {cons} (Lift: {row['lift']:.2f})", 0, 1)
        pdf.ln(10)
        pdf.set_font("Arial", size=10)
        pdf.cell(0, 10, "Report generated by BundleAI • By Freda Erinmwingbovo", 0, 1, 'C')
        return pdf.output(dest='S').encode('latin1')

    pdf_data = create_pdf()

    # === DOWNLOAD BUTTONS ===
    col1, col2 = st.columns(2)
    with col1:
        st.download_button("Download Full Report as PDF", pdf_data, "BundleAI_Report.pdf", "application/pdf")
    with col2:
        st.download_button("Download Raw Data as CSV", elite.to_csv(index=False), "bundleai_data.csv", "text/csv")

    st.markdown("---")
    st.markdown("<p style='text-align:center; color:#666'>Powered by FP-Growth • Built with ❤️ by Freda Erinmwingbovo</p>", unsafe_allow_html=True)

else:
    st.info("Upload your CSV to get started — no setup needed!")
